name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Build
        run: make

      - name: Check format
        run: make check-format

      - name: Run tests
        run: make check

      - name: Clean
        run: make clean
